export const PATTERN_NOTE_CHANGE = "PATTERN_NOTE_CHANGE";
export const TRANSPORT_STEP = "TRANSPORT_STEP";
export const TRANSPORT_START = "TRANSPORT_START";
export const TRANSPORT_STOP = "TRANSPORT_STOP";
